### ISSUE TITLE
Per device DNS settings

### ISSUE THREAD

**Issue by graysky2** [deathbybandaid/AdvancedPi#12]
https://github.com/deathbybandaid/piadvanced/blob/master/piholetweaks/dnsmasqtweaks/04-bypass.conf

I tried using this but I am finding that the target device is still using pi-hole as the DNS rather than google.  I do not have pi-hole configured to assign devices IP addresses (router does that).  Is that the reason why it fails?  My goal is to allow certain devices to be unprotected by pihole.

Thank you.

```
dhcp-option=tag:googlesdns1,6,8.8.8.8
dhcp-option=tag:googlesdns2,6,8.8.4.4
dhcp-host=c2:15:ef:16:a5:ba,set:googlesdns1
```

**Comment by deathbybandaid** [comment]
Yes. This config needs to be applied when Pi-hole is serving DHCP as well.

**Comment by graysky2** [comment]
Thanks for confirming... turns out I can use it on my router (above pihole) with the desired effect.  Thanks for  sharing.
