### ISSUE TITLE
pihole-bypass causing dnsmasq/pihole not to run

### ISSUE THREAD

**Issue by paulvil** [deathbybandaid/AdvancedPi#3]
On line 55 of pihole.sh, 04-bypass.conf is wget'd. On line 22 of that conf, 
`dhcp-host=MA:CA:DD:R:ES:SS,set:YOURTAGHERE` is uncommented and none of the scripts try to setup it up.

When dnsmasq (and by extension pihole) attempts to run, it errors out due to the bad hex value.

I think the easiest fix would be to comment out line 22 of 04-bypass.conf

**Comment by deathbybandaid** [comment]
Easy enough fix,,, thanks for spotting that!!!

That's how those configs are meant to be, disabled by default

Isn't it always just the tiniest little typos!!??
