### ISSUE TITLE
How do i revert the theme and user interface back to the original?

### ISSUE THREAD

**Issue by DarthKeizer** [deathbybandaid/AdvancedPi#9]
How do i revert the theme and user interface back to the original?
Can't seem to find it, can you help out? Thanks :)!

**Comment by deathbybandaid** [comment]
one of the threads on discourse explains how to reset,,, I think it's something like 

git reset --hard

but I don't remember offhand

**Comment by DarthKeizer** [comment]
I mean the raspberry pi theme, not the one from pihole :)!

**Comment by DarthKeizer** [comment]
Hey @deathbybandaid 

I fixed the problem by using:

`sudo apt-get install raspberrypi-ui-mods
`

Issue is solved :+1:

**Comment by deathbybandaid** [comment]
The message of the day?

**Comment by DarthKeizer** [comment]
@deathbybandaid no some theme you get along with installing. A different GUI, but you can close the issue 👍
